name: shared_expenses
description: Shared Expense Manager


publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.1.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.1
  flutter_icons: ^1.1.0
  page_transition: ^2.0.4
  animated_bottom_navigation_bar: ^0.3.2
  fl_chart: ^0.40.6
  date_time_picker: "^2.0.0"
  intl: ^0.17.0
  select_form_field: "^2.0.0"
  scoped_model: ^1.1.0
  url_launcher: ^6.0.3
  path_provider: ^2.0.1
  shared_preferences: ^2.0.5
  file_picker: ^4.3.0
  animations: ^2.0.0
  screenshot: ^1.2.3
  pie_chart: ^5.1.0
  sqflite: ^2.0.1
  share_plus:
  image_gallery_saver: '^1.7.1'

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0
  flutter_launcher_icons: ^0.9.2
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/budget.png"



# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    # - assets/images/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
